[package]
name = "mix"
version = "0.1.0"
authors = ["twenty"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.11.1"
dirs = "3.0.1"
